### ISSUE TITLE
:Inherit is void

### ISSUE THREAD

**Issue by mehdikhawari** [protesilaos/cursory#1]
Hi Prot!

Thank you for all your efforts. I appropriate it.

I am trying to use the cursory package without any configuration as follows:
``` emacs-lisp
(use-package cursory
  :demand t)
```

When I try `cursory-set-preset`, I get the following error message:
`cursory--get-preset-properties: Symbol’s value as variable is void: inherit`

Straight.el also complains, when it tries to byte-compile it:

```
In cursory--get-inherit-name:
cursory.el:262:35: Warning: `(inherit (plist-get (alist-get preset
    cursory-presets) :inherit))' is a malformed function
cursory.el:262:35: Warning: Unused lexical argument `preset'
cursory.el:265:34: Warning: reference to free variable `inherit'

In end of data:
cursory.el:264:4: Warning: the function `when-let*' might not be defined at
    runtime.
Done (Total of 1 file compiled, 1 skipped)
```
Do I miss something?

**Comment by protesilaos** [comment]
Hello @mehdikhawari!

It seems like there is a mismatch of versions, such as an old byte compiled file.

I used `emacs -Q` on the command-line and then evaluated this:

```elisp
(require 'cursory "~/.emacs.d/elpa/cursory-1.0.0.0.20230708.103719/cursory.el")

(call-interactively 'cursory-set-preset)
```

I could select a preset and it works properly.

Maybe you can try this so that we isolate the issue?  Modify the above code to include the path to your `cursory.el` file.

**Comment by mehdikhawari** [comment]
I can also select a preset in `emacs -Q`. But when using straight.el as package manager, I still get the error message. Maybe I can ask there. Thank you again.

**Comment by protesilaos** [comment]
> From: Mehdi Khawari ***@***.***>
> Date: Thu, 20 Jul 2023 06:29:06 -0700
>
> I can also select a preset in `emacs -Q`. But when using straight.el
> as package manager, I still get the error message. Maybe I can ask
> there. Thank you again.

If it is limited to straight, then it probably is worth checking with
the maintainer there.  Please send me the link so I can follow along and
make any required changes.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by mehdikhawari** [comment]
Sorry for the late reply.

https://github.com/radian-software/straight.el/issues/1106#issue-1830802399

**Comment by progfolio** [comment]
The issue is that cursory does not `(eval-when-compile (require 'subr-x))`.
Pre Emacs 29, this is where when-let* is defined. In 29+ it was moved to subr.el.

@protesilaos 
> I used emacs -Q on the command-line and then evaluated this:

> (require 'cursory "~/.emacs.d/elpa/cursory-1.0.0.0.20230708.103719/cursory.el")

> (call-interactively 'cursory-set-preset)

> I could select a preset and it works properly.

That does not load the byte compiled file, so it side-steps the issue.

**Comment by protesilaos** [comment]
Thank you @mehdikhawari for doing this and @progfolio for suggesting the fix!  I did not check the original warning message carefully...
